/*
auto-generated by: https://github.com/pmndrs/gltfjsx
GOOGLE_processor_version: 294144208
*/
import React from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Jet(props) {
  const { nodes, materials } = useGLTF('models/plane/1397 Jet.gltf')

  return (
    <group>
      <group scale={[ 0.05, 0.05, 0.05 ]}>
        <mesh material={materials.Mat} geometry={nodes['node-0'].geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('models/plane/1397 Jet.gltf')
