/*
auto-generated by: https://github.com/pmndrs/gltfjsx
GOOGLE_processor_version: 294144208
*/
import React, { useRef } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const ref = useRef()
  const { nodes, materials } = useGLTF('models/plane/1397 Jet.gltf')

  useFrame(state => {
    const time = state.clock.getElapsedTime()
    ref.current.rotation.z = Math.sin(time)
    // ref.current.position.z += 0.1
    ref.current.matrix.needsUpdate = true
  })

  return (
    <group position={[0, 9.0, 0]} ref={ref} {...props}>
      <group scale={[ 0.05, 0.05, 0.05 ]}>
        <mesh material={materials.Mat} geometry={nodes['node-0'].geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('models/plane/1397 Jet.gltf')
